# Generated by Django 3.0.3 on 2020-07-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=200)),
                ('recipe_content', models.TextField()),
                ('recipe_date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
