# Generated by Django 3.0.3 on 2020-07-13 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_content',
            new_name='conteudo_receita',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_title',
            new_name='titulo_receita',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_date',
        ),
        migrations.AddField(
            model_name='recipe',
            name='data_receita',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publicação'),
            preserve_default=False,
        ),
    ]
