# Generated by Django 3.0.3 on 2020-07-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200713_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Receita',
        ),
    ]
