# Generated by Django 3.0.3 on 2020-07-13 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200713_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 15, 49, 46, 300532), verbose_name='Data publicação'),
        ),
    ]
