# Generated by Django 3.0.3 on 2020-07-14 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200713_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem_preview',
            field=models.ImageField(default='/static/img/default_image.png', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='resumo_receita',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 13, 18, 43, 337607), verbose_name='Data publicação'),
        ),
    ]
