# Generated by Django 3.0.3 on 2020-07-15 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200714_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('desc_produto', models.CharField(default='', max_length=255)),
                ('imagem_produto', models.ImageField(default='static/default_image.png', upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 15, 39, 27, 884725), verbose_name='Data publicação'),
        ),
    ]
