# Generated by Django 3.0.3 on 2020-07-15 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200715_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 15, 41, 14, 480600), verbose_name='Data publicação'),
        ),
    ]
