# Generated by Django 3.0.3 on 2020-07-15 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200715_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 15, 46, 27, 287426), verbose_name='Data publicação'),
        ),
    ]
