# Generated by Django 3.0.3 on 2020-08-04 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200715_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='rendimento_receita',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='receita',
            name='tempo_receita',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 16, 46, 13, 683112), verbose_name='Data publicação'),
        ),
    ]
