# Generated by Django 3.0.3 on 2020-08-11 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200811_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='desc',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 10, 29, 18, 221123), verbose_name='Data publicação'),
        ),
    ]
